
name: releases pub

on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: zip
        run: |
          tar -czvf 4k_wallpaper.tar.gz images/4k_*
          tar -czvf wallpaper.tar.gz images/bing_*
          tar -czvf wallpaper`echo $(date +"%Y-%m")`.tar.gz images/4k_`echo $(date +"%Y-%m")`*
          tar -czvf 4k_wallpaper`echo $(date +"%Y-%m")`.tar.gz images/bing_`echo $(date +"%Y-%m")`*

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y-%m")"
          touch release.txt
          "Pack pictures every month " >> release.txt

      - name: Upload  to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: |
            wallpaper*
            4k*
